# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""
Ngen Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the NextGen Framework model.

This module registers Ngen-specific configuration components with the
ModelRegistry, enabling the core config system to remain model-agnostic.

PHASE 2 REFACTORING: This adapter now uses AutoGeneratedConfigAdapter
to auto-generate defaults and transformers from Pydantic Field declarations.
All defaults are maintained in NgenConfig (model_configs.py) for single
source of truth.
"""

from typing import Any, Dict

from symfluence.core.config.models.model_configs import NGENConfig
from symfluence.models.base import AutoGeneratedConfigAdapter, ConfigValidationError


def _normalize_ngen_module_name(module_name: str) -> str:
    token = module_name.strip().upper().replace('-', '').replace('_', '').replace(' ', '')
    aliases = {
        'NOAHOWP': 'NOAH',
        'NOAH': 'NOAH',
        'SLOTH': 'SLOTH',
        'PET': 'PET',
        'CFE': 'CFE',
        'TOPMODEL': 'TOPMODEL',
        'SACSMA': 'SACSMA',
        'SNOW17': 'SNOW17',
    }
    return aliases.get(token, token)


def _get_ngen_config_value(config: Dict[str, Any], flat_key: str, nested_key: str = None) -> Any:
    """
    Get NGEN configuration value from config supporting both flat and nested formats.

    Supports:
    1. Flat format (legacy): NGEN_MODULES_TO_CALIBRATE: "CFE,PET"
    2. Nested format (new):
       model:
         ngen:
           modules_to_calibrate: "CFE,PET"
    3. Mixed format: Both present (flat takes precedence for backwards compat)

    Args:
        config: Configuration dictionary (may be flat or nested)
        flat_key: Flat config key (e.g., 'NGEN_MODULES_TO_CALIBRATE')
        nested_key: Nested config key (e.g., 'modules_to_calibrate')
                    If not provided, derived from flat_key

    Returns:
        Configuration value if found, None otherwise
    """
    # Try flat key first (backwards compatibility, highest priority)
    flat_value = config.get(flat_key)
    if flat_value:
        return flat_value

    # Derive nested key from flat key if not provided
    if nested_key is None:
        # NGEN_MODULES_TO_CALIBRATE -> modules_to_calibrate
        nested_key = flat_key.replace('NGEN_', '').lower()

    # Check if 'model' section exists with 'ngen' subsection
    model_section = config.get('model')
    if isinstance(model_section, dict):
        ngen_section = model_section.get('ngen')
        if isinstance(ngen_section, dict):
            nested_value = ngen_section.get(nested_key)
            if nested_value:
                return nested_value

    # Try alternative nested path: ngen directly in config
    # (in case config is partially flattened)
    ngen_section = config.get('ngen')
    if isinstance(ngen_section, dict):
        nested_value = ngen_section.get(nested_key)
        if nested_value:
            return nested_value

    return None


class NgenConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for NGEN model with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from NGENConfig
    Pydantic model. Only custom validation logic is implemented here.
    """

    def __init__(self, model_name: str = 'NGEN'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return NGEN Pydantic configuration schema."""
        return NGENConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """
        Validate Ngen-specific configuration.

        Supports both flat and nested config formats:
        - Flat:   NGEN_MODULES_TO_CALIBRATE: "SACSMA", NGEN_SACSMA_PARAMS_TO_CALIBRATE: "UZTWM"
        - Nested: model.ngen.modules_to_calibrate: "SAC-SMA", model.ngen.sacsma_params_to_calibrate: "UZTWM"

        Validation checks:
        1. All modules in NGEN_MODULES_TO_CALIBRATE have parameters defined
        2. All modules in NGEN_MODULES_TO_CALIBRATE are in NGEN_MODULES_SELECTED
        """
        # Get modules to calibrate from either flat or nested config
        modules_str = _get_ngen_config_value(config, 'NGEN_MODULES_TO_CALIBRATE', 'modules_to_calibrate')
        if not modules_str:
            return

        modules = modules_str.split(',')
        for module in modules:
            module = _normalize_ngen_module_name(module)
            # Use helper to find parameter value in either flat or nested format
            param_flat_key = f'NGEN_{module}_PARAMS_TO_CALIBRATE'
            param_nested_key = f'{module.lower()}_params_to_calibrate'
            param_value = _get_ngen_config_value(config, param_flat_key, param_nested_key)
            if not param_value:
                raise ConfigValidationError(
                    f"NGEN configuration incomplete. Module '{module}' is selected for "
                    f"calibration but parameter list is missing or empty. "
                    f"Provide one of:\n"
                    f"  - Flat format:   {param_flat_key}: 'param1,param2,...'\n"
                    f"  - Nested format: model.ngen.{param_nested_key}: 'param1,param2,...'"
                )

        # Get selected modules from either flat or nested config
        selected_str = _get_ngen_config_value(config, 'NGEN_MODULES_SELECTED', 'modules_selected')
        if not selected_str:
            selected_str = 'SLOTH,PET,CFE'  # Default if not provided
        
        selected = {_normalize_ngen_module_name(m) for m in selected_str.split(',') if m.strip()}
        calibrate = {_normalize_ngen_module_name(m) for m in modules_str.split(',') if m.strip()}
        not_selected = calibrate - selected
        if not_selected:
            raise ConfigValidationError(
                f"NGEN_MODULES_TO_CALIBRATE contains modules not in "
                f"NGEN_MODULES_SELECTED: {not_selected}. Add them to "
                f"NGEN_MODULES_SELECTED or remove them from NGEN_MODULES_TO_CALIBRATE."
            )


# Backward compatibility alias
NGENConfigAdapter = NgenConfigAdapter
